openapi: 3.0.1
info:
  title: CJWAPI_V6
  version: 1.0.0
servers:
  - url: /
security:
  - default: []
paths:
  /7be1a9be-514e-4cf4-be91-7910b49d8d17:
    get:
      parameters: []
      responses:
        '200':
          description: ok
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: null
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}

x-wso2-production-endpoints:
  urls:
    - 'http://run.mocky.io/v3/'
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - 'http://run.mocky.io/v3/'
  type: http
x-wso2-basePath: /bny/v6
